export const SECURITY_LOG_STATUS = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
} as const;

export type SecurityLogStatus = (typeof SECURITY_LOG_STATUS)[keyof typeof SECURITY_LOG_STATUS];

export const SECURITY_ACTOR_ROLE = {
  ADMIN: "ADMIN",
  STAFF: "STAFF",
  EMPLOYEE: "EMPLOYEE",
  PUBLIC: "Public",
  SYSTEM: "System",
} as const;

export type SecurityActorRole = (typeof SECURITY_ACTOR_ROLE)[keyof typeof SECURITY_ACTOR_ROLE];

export const SECURITY_EVENT_TYPE = {
  AUTH_FORCE_LOGOUT_OTHERS: "AUTH_FORCE_LOGOUT_OTHERS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_PASSWORD_CHANGED: "AUTH_PASSWORD_CHANGED",
  AUTH_PASSWORD_RESET_REQUESTED: "AUTH_PASSWORD_RESET_REQUESTED",
  AUTH_PASSWORD_RESET_SUCCESS: "AUTH_PASSWORD_RESET_SUCCESS",
  AUTH_REFRESH_FAILED: "AUTH_REFRESH_FAILED",
  AUTH_REFRESH_SUCCESS: "AUTH_REFRESH_SUCCESS",
  CRON_CHECK_EXPIRY_RUN: "CRON_CHECK_EXPIRY_RUN",
  CRON_DOCUMENT_EXPIRED: "CRON_DOCUMENT_EXPIRED",
  DOCUMENT_APPROVED: "DOCUMENT_APPROVED",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",
  DOCUMENT_DOWNLOADED: "DOCUMENT_DOWNLOADED",
  DOCUMENT_PERMANENTLY_DELETED: "DOCUMENT_PERMANENTLY_DELETED",
  DOCUMENT_REJECTED: "DOCUMENT_REJECTED",
  DOCUMENT_RESTORED: "DOCUMENT_RESTORED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  EMPLOYEE_ACCOUNT_UPDATED: "EMPLOYEE_ACCOUNT_UPDATED",
  EMPLOYEE_CREATED: "EMPLOYEE_CREATED",
  EMPLOYEE_DELETED: "EMPLOYEE_DELETED",
  EMPLOYEE_EXPORTED: "EMPLOYEE_EXPORTED",
  EMPLOYEE_PERMANENTLY_DELETED: "EMPLOYEE_PERMANENTLY_DELETED",
  EMPLOYEE_RESTORED: "EMPLOYEE_RESTORED",
  EMPLOYEE_UPDATED: "EMPLOYEE_UPDATED",
  MASTER_DATA_CREATED: "MASTER_DATA_CREATED",
  MASTER_DATA_DELETED: "MASTER_DATA_DELETED",
  MASTER_DATA_UPDATED: "MASTER_DATA_UPDATED",
  SYSTEM_SETTING_UPDATED: "SYSTEM_SETTING_UPDATED",
} as const;

export type SecurityEventType = (typeof SECURITY_EVENT_TYPE)[keyof typeof SECURITY_EVENT_TYPE];
